//! Host-side implementation of the `et:ws-wasi` WIT world.
//!
//! `HostState` is the per-store object held by `wasmtime::Store<HostState>`. It
//! owns the WASI Preview 2 context (for stdio/env/random/etc.), an HTTP client
//! used by the storage interface, the ws connection state, and the wgpu device
//! used by the gfx interface.

use std::sync::Arc;

use tokio::sync::Mutex;
use wasmtime::component::ResourceTable;
use wasmtime_wasi::{DirPerms, FilePerms, WasiCtx, WasiCtxBuilder, WasiCtxView, WasiView};

mod error;
mod log;
pub mod wasi_keyvalue;
pub mod wasi_nn;
pub mod wasi_webgpu;
pub mod ws;

pub use self::error::{
    KvErrExt, RequestDeviceErrExt, WitErrExt, WsDecodeErrExt, WsTransportErrExt, kv_not_implemented,
};
pub use self::ws::WsBackend;

#[non_exhaustive]
pub struct HostState {
    pub wasi_ctx: WasiCtx,
    pub resource_table: ResourceTable,

    /// WebSocket URL of the ws-server (e.g. `ws://localhost:8080/ws`).
    pub ws_url: String,

    /// How long the host waits for `et-connect-ack`; `None` waits forever.
    pub connect_ack_timeout: Option<std::time::Duration>,

    /// Typed REST client for the ws-server (modules + per-agent storage).
    /// Generated by `cargo-progenitor` from `generated/specs/rest.yaml`.
    pub rest: et_rest_client::Client,
    pub ws: Arc<Mutex<Option<WsBackend>>>,
    /// wasi-nn context. Constructed once at startup so model loads + compute
    /// reuse the same `ort` session pool across calls.
    pub wasi_nn_ctx: wasmtime_wasi_nn::wit::WasiNnCtx,
}

impl HostState {
    #[must_use]
    #[expect(
        clippy::same_name_method,
        reason = "convention: HostState::new mirrors WasiCtxBuilder/ResourceTable/Client constructors used here"
    )]
    pub fn new(
        http_base: &str,
        ws_url: String,
        connect_ack_timeout: Option<std::time::Duration>,
        coverage: bool,
    ) -> Self {
        let mut builder = WasiCtxBuilder::new();
        #[expect(
            unused_results,
            clippy::expect_used,
            reason = "WasiCtxBuilder setters return &mut Self; a coverage-preopen failure is a misconfigured test run"
        )]
        {
            builder.inherit_stdio().inherit_env();
            // Instrumented guests write their minicov `.profraw` to `/cov`; map it to target/wasi-cov so the
            // wasi-cov task finds it. Repo-root-anchored (not CWD) so it lands consistently under nextest.
            if coverage {
                let cov_dir = edge_toolkit::config::get_project_root().join("target/wasi-cov");
                fs_err::create_dir_all(&cov_dir).expect("create target/wasi-cov");
                builder
                    .preopened_dir(&cov_dir, "/cov", DirPerms::all(), FilePerms::all())
                    .expect("preopen /cov for wasm coverage");
            }
        }
        let wasi_ctx = builder.build();

        Self {
            wasi_ctx,
            resource_table: ResourceTable::new(),
            ws_url,
            connect_ack_timeout,
            rest: et_rest_client::Client::new(http_base),
            ws: Arc::new(Mutex::new(None)),
            wasi_nn_ctx: wasi_nn::new_ctx(),
        }
    }
}

impl WasiView for HostState {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.wasi_ctx,
            table: &mut self.resource_table,
        }
    }
}
