[tools]
action-validator = "latest"
"cargo:taplo-cli" = "latest"
"cargo:wasm-pack" = "latest"
"chromedriver" = "146"
cmake = "latest"
dprint = "latest"
editorconfig-checker = "latest"
"github:block/goose" = "latest"
ollama = "latest"
osv-scanner = "latest"
pipx = "latest"
"pipx:cmake" = "latest"
protoc = "latest"
rust = { version = "latest", components = "clippy" }
typos = "latest"

# grex is just a convenient way to depends on all of the checker tools at once
grex = { depends = [
  "cargo:taplo-cli",
  "dprint",
  "editorconfig-checker",
  "osv-scanner",
  "rust",
  "rust@nightly",
  "typos",
], "version" = "latest" }

[tasks]
dprint-check = "dprint check"
dprint-fmt = "dprint fmt"
editorconfig-check = "ec"

[tasks.fmt]
depends = ["cargo-fmt", "dprint-fmt", "taplo-fmt"]
description = "Run repository formatters"

[tasks.install-nightly]
run = "rustup toolchain install nightly --component rustfmt"


[tasks.check-phase-1]
depends = ["cargo-check", "cargo-clippy", "dprint-check", "editorconfig-check", "taplo-check", "typos"]
description = "Run repository checks (phase 1: even if no Cargo.lock exists)"

[tasks.check]
depends = [
  "cargo-check",
  "cargo-clippy",
  "cargo-fmt-check",
  "dprint-check",
  "editorconfig-check",
  "osv-scanner",
  "taplo-check",
  "typos",
]
description = "Run repository checks"

[tasks.cargo-check]
run = "cargo check --workspace"

[tasks.cargo-fmt]
depends = ["install-nightly"]
run = "cargo +nightly fmt"

# Not accepted per https://mise.jdx.dev/tasks/task-configuration.html :

#[tasks.cargo-fmt.tools.rust]
#version = "nightly"
#components = "rustfmt"

[tasks.cargo-fmt-check]
depends = ["install-nightly"]
run = "cargo +nightly fmt -- --check"

#[tasks.cargo-fmt-check.tools.rust]
#version = "nightly"
#components = "rustfmt"

[tasks.cargo-clippy]
run = "cargo clippy --workspace"

[tasks.taplo-fmt]
run = "taplo format"

[tasks.taplo-check]
run = "taplo lint"

[tasks.typos]
run = "typos"

[tasks.osv-scanner]
depends = ["cargo-check"]
run = "osv-scanner --lockfile Cargo.lock"

[tasks.ws-server]
description = "Run the WebSocket server"
dir = "services/ws-server"
run = "cargo run"

[tasks.build-ws-wasm-agent]
description = "Build the WebSocket WASM client"
dir = "services/ws-wasm-agent"
run = "wasm-pack build --target web"

[tasks.test-ws-wasm-agent-firefox]
description = "Run headless Firefox tests for the WebSocket WASM client"
dir = "services/ws-wasm-agent"
run = "wasm-pack test --headless --firefox"

[tasks.ws-e2e-firefox]
depends = ["test-ws-wasm-agent-firefox", "ws-server"]
description = "Run both the ws-server and ws-wasm-agent using Firefox"

[tasks.test-ws-wasm-agent-chrome]
description = "Run headless Chrome tests for the WebSocket WASM client"
dir = "services/ws-wasm-agent"
run = "env CHROMEDRIVER=\"$(mise where chromedriver)/bin/chromedriver\" wasm-pack test --headless --chrome"

[tasks.ws-e2e-chrome]
depends = ["test-ws-wasm-agent-chrome", "ws-server"]
description = "Run both the ws-server and ws-wasm-agent using Chrome"
