[tools]
"cargo:taplo-cli" = "latest"
"cargo:wasm-pack" = "latest"
"chromedriver" = "146"
"github:block/goose" = "latest"
"pipx:cmake" = "latest"
cmake = "latest"
editorconfig-checker = "latest"
ollama = "latest"
osv-scanner = "latest"
pipx = "latest"
protoc = "latest"
rust = "latest"
typos = "latest"

[tasks.fmt]
description = "Run repository formatters"
depends = ["cargo-fmt", "taplo-fmt"]

[tasks.check]
description = "Run repository checks"
depends = [
  "cargo-check",
  "cargo-fmt-check",
  "typos",
  "taplo-check",
  "osv-scanner",
]

[tasks.cargo-check]
run = "cargo check --workspace"

[tasks.cargo-fmt]
run = "cargo +nightly fmt"

[tasks.cargo-fmt-check]
run = "cargo +nightly fmt -- --check"

[tasks.taplo-fmt]
run = "taplo format"

[tasks.taplo-check]
run = "taplo lint"

[tasks.typos]
run = "typos"

[tasks.osv-scanner]
run = "osv-scanner --lockfile Cargo.lock"

[tasks.ws-server]
description = "Run the WebSocket server"
dir = "services/ws-server"
run = "cargo run"

[tasks.build-ws-wasm-agent]
description = "Build the WebSocket WASM client"
dir = "services/ws-wasm-agent"
run = "wasm-pack build --target web"

[tasks.test-ws-wasm-agent-firefox]
description = "Run headless Firefox tests for the WebSocket WASM client"
dir = "services/ws-wasm-agent"
run = "wasm-pack test --headless --firefox"

[tasks.ws-e2e-firefox]
description = "Run both the ws-server and ws-wasm-agent using Firefox"
depends = ["ws-server", "test-ws-wasm-agent-firefox"]

[tasks.test-ws-wasm-agent-chrome]
description = "Run headless Chrome tests for the WebSocket WASM client"
dir = "services/ws-wasm-agent"
run = "env CHROMEDRIVER=\"$(mise where chromedriver)/bin/chromedriver\" wasm-pack test --headless --chrome"

[tasks.ws-e2e-chrome]
description = "Run both the ws-server and ws-wasm-agent using Chrome"
depends = ["ws-server", "test-ws-wasm-agent-chrome"]
