[workspace.package]
edition = "2024"
license = "Apache-2.0 or MIT"
repository = "https://github.com/edge-toolkit/core"
rust-version = "1.87.0"

[workspace]
members = [
  "libs/edge-toolkit",
  "libs/et-otlp",
  "libs/otlp-mock",
  "libs/web",
  "services/ws-modules/audio1",
  "services/ws-modules/bluetooth",
  "services/ws-modules/comm1",
  "services/ws-modules/data1",
  "services/ws-modules/face-detection",
  "services/ws-modules/geolocation",
  "services/ws-modules/graphics-info",
  "services/ws-modules/har1",
  "services/ws-modules/nfc",
  "services/ws-modules/pyo3-split-learning-mit",
  "services/ws-modules/sensor1",
  "services/ws-modules/speech-recognition",
  "services/ws-modules/video1",
  "services/ws-modules/wasi-comm1",
  "services/ws-modules/wasi-data1",
  "services/modules",
  "services/storage",
  "services/ws",
  "services/ws-pyo3-runner",
  "services/ws-server",
  "services/ws-wasm-agent",
  "services/ws-wasi-runner",
  "services/ws-test-server",
  "utilities/cli",
  "utilities/onnx",
]
resolver = "2"

[workspace.dependencies]
actix = "0.13"
actix-rt = "2"
actix-web = { version = "4", features = ["rustls-0_23"] }
anyhow = "1.0"
base64 = "0.22.1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.4", features = ["derive"] }
edge-toolkit = { path = "libs/edge-toolkit" }
et-otlp = { path = "libs/et-otlp" }
et-web = { path = "libs/web" }
lets_find_up = "0.0.4"
log = "0.4"
onnx-extractor = "0.3"
opentelemetry = "0.31"
rstest = "0.26"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde-env = "0.3"
serde-inline-default = "1.0"
serde_default = "0.2"
serde_json = "1"
serde_yaml = "0.9"
tempfile = "3"
thiserror = "2"
toml = "0.8"
tracing = "0.1"
tracing-actix-web = { version = "0.7", default-features = false, features = [
  "emit_event_on_error",
  "opentelemetry_0_31",
  "uuid_v7",
] }
tracing-opentelemetry = "0.32"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["serde", "v4", "v7"] }
