[package]
name = "et-ws-server"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
actix-rt.workspace = true
actix-web.workspace = true
chrono.workspace = true
clap.workspace = true
edge-toolkit.workspace = true
et-modules-service = { path = "../modules" }
et-otlp.workspace = true
et-storage-service = { path = "../storage" }
et-ws-service = { path = "../ws" }
futures-util = "0.3"
local-ip-address = "0.6"
log.workspace = true
qr2term = "0.3"
rcgen = "0.14"
regex = { version = "1.12", default-features = false }
rustls = "0.23"
secrecy.workspace = true
serde.workspace = true
serde-env.workspace = true
serde-inline-default.workspace = true
serde_default.workspace = true
serde_json.workspace = true
serde_yaml = "0.9"
tokio = { version = "1", features = ["full"] }
tracing.workspace = true
tracing-actix-web.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
