use std::collections::BTreeSet;
use std::ffi::OsString;
use std::fs;
use std::path::{Component, Path, PathBuf};

use anyhow::{Context, Result, anyhow};
use clap::{Parser, Subcommand, ValueEnum};
use edge_toolkit::input::ClusterInput;

#[derive(Parser)]
#[command(name = "et-cli")]
#[command(about = "Edge Toolkit Management CLI")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Generate deployment config from a cluster input YAML.
    GenerateDeployment {
        #[arg(long, default_value = "verification/local/input/facility-security-example.yaml")]
        input_file: PathBuf,
        #[arg(long, default_value = "verification/local/output/facility-security-example/")]
        output_dir: PathBuf,
        #[arg(long, value_enum)]
        output_type: Option<OutputType>,
    },
}

#[derive(Debug, Clone, Copy, ValueEnum)]
enum OutputType {
    Mise,
}

const WS_WASM_AGENT_SOURCES: &str = concat!(
    "sources = [\"Cargo.toml\", \"src/**/*.rs\", \"../../Cargo.toml\", ",
    "\"../../Cargo.lock\", \"../../libs/**/*.rs\"]",
);
const WS_MODULE_SOURCES: &str = concat!(
    "sources = [\"Cargo.toml\", \"src/**/*.rs\", \"../../../Cargo.toml\", ",
    "\"../../../Cargo.lock\", \"../../../libs/**/*.rs\", ",
    "\"../../ws-wasm-agent/Cargo.toml\", \"../../ws-wasm-agent/src/**/*.rs\"]",
);

fn main() -> Result<()> {
    let cli = Cli::parse();

    match &cli.command {
        Commands::GenerateDeployment {
            input_file,
            output_dir,
            output_type,
        } => generate_deployment(input_file, output_dir, *output_type)?,
    }

    Ok(())
}

fn generate_deployment(input_file: &Path, output_dir: &Path, output_type: Option<OutputType>) -> Result<()> {
    println!("Reading cluster input from: {:?}", input_file);
    let content =
        fs::read_to_string(input_file).with_context(|| format!("Failed to read input file: {:?}", input_file))?;

    let cluster: ClusterInput = serde_yaml::from_str(&content).with_context(|| "Failed to parse cluster input YAML")?;
    let output_type = output_type
        .map(Ok)
        .or_else(|| cluster.deployment_type.as_deref().map(output_type_from_input))
        .unwrap_or(Ok(OutputType::Mise))?;

    if !output_dir.exists() {
        fs::create_dir_all(output_dir)
            .with_context(|| format!("Failed to create output directory: {:?}", output_dir))?;
    }

    match output_type {
        OutputType::Mise => generate_mise_deployment(input_file, &cluster, output_dir),
    }
}

fn output_type_from_input(value: &str) -> Result<OutputType> {
    OutputType::from_str(value, true).map_err(|_| {
        anyhow!(
            "Unsupported deployment_type {:?}. Supported values are currently: mise",
            value
        )
    })
}

fn generate_mise_deployment(input_file: &Path, cluster: &ClusterInput, output_dir: &Path) -> Result<()> {
    let output_path = output_dir.join(".mise.toml");
    let mut content = String::new();

    content.push_str("# Generated by et-cli. Do not edit by hand.\n");
    content.push_str(&format!("# Source input: {}\n\n", input_file.display()));

    let workspace_root =
        std::env::current_dir().with_context(|| "Failed to resolve current working directory for mise tasks")?;
    let output_abs = absolute_from(&workspace_root, output_dir);
    let module_names = cluster_module_names(cluster);
    let build_task_names = module_names
        .iter()
        .map(|module_name| module_build_task_name(module_name))
        .collect::<Vec<_>>();

    content.push_str("[tasks.ws-server]\n");
    content.push_str("description = \"Run the WebSocket server\"\n");
    content.push_str(&format!(
        "dir = {}\n",
        toml_string(
            &relative_path_from(&output_abs, &workspace_root.join("services/ws-server"))
                .display()
                .to_string()
        )
    ));
    content.push_str("run = \"cargo run\"\n\n");

    content.push_str("[tasks.ws-server.env]\n");
    content.push_str("OTLP_AUTH_PASSWORD = \"1234\"\n");
    content.push_str("OTLP_AUTH_USERNAME = \"root@example.com\"\n\n");

    content.push_str("[tasks.build-ws-wasm-agent]\n");
    content.push_str("description = \"Build the WebSocket WASM client\"\n");
    content.push_str(&format!(
        "dir = {}\n",
        toml_string(
            &relative_path_from(&output_abs, &workspace_root.join("services/ws-wasm-agent"))
                .display()
                .to_string()
        )
    ));
    content.push_str("run = \"wasm-pack build . --target web -- -Z build-std=std,panic_abort\"\n");
    content.push_str(WS_WASM_AGENT_SOURCES);
    content.push('\n');
    content.push_str("outputs = [\"pkg/**/*\"]\n\n");

    content.push_str("[tasks.build-ws-wasm-agent.env]\n");
    content.push_str(
        "RUSTFLAGS = \"-C target-cpu=mvp -C target-feature=+mutable-globals,+sign-ext,+nontrapping-fptoint\"\n",
    );
    content.push_str("RUSTUP_TOOLCHAIN = \"nightly\"\n\n");

    for (module_name, task_name) in module_names.iter().zip(build_task_names.iter()) {
        content.push_str(&format!("[tasks.{}]\n", toml_string(task_name)));
        content.push_str(&format!(
            "description = {}\n",
            toml_string(&format!("Build the {module_name} workflow WASM module"))
        ));
        content.push_str(&format!(
            "dir = {}\n",
            toml_string(
                &relative_path_from(
                    &output_abs,
                    &workspace_root.join("services/ws-modules").join(module_name),
                )
                .display()
                .to_string()
            )
        ));
        content.push_str("run = \"wasm-pack build . --target web\"\n");
        content.push_str(WS_MODULE_SOURCES);
        content.push('\n');
        content.push_str("outputs = [\"pkg/**/*\"]\n\n");
    }

    content.push_str("[tasks.build-wasm]\n");
    content.push_str(&format!(
        "description = {}\n",
        toml_string(&format!("Build WebAssembly artifacts for {}", cluster.cluster_name))
    ));
    content.push_str("depends = [");
    content.push_str(&toml_string("build-ws-wasm-agent"));
    for task_name in &build_task_names {
        content.push_str(", ");
        content.push_str(&toml_string(task_name));
    }
    content.push_str("]\n\n");

    content.push_str("[tasks.generated-scenario]\n");
    content.push_str(&format!(
        "description = {}\n",
        toml_string(&format!(
            "Build and run generated scenario for {}",
            cluster.cluster_name
        ))
    ));
    content.push_str("depends = [\"build-wasm\"]\n");
    content.push_str(&format!(
        "dir = {}\n",
        toml_string(
            &relative_path_from(&output_abs, &workspace_root.join("services/ws-server"))
                .display()
                .to_string()
        )
    ));
    content.push_str("run = \"cargo run\"\n\n");

    content.push_str("[tasks.generated-scenario.env]\n");
    content.push_str("OTLP_AUTH_PASSWORD = \"1234\"\n");
    content.push_str("OTLP_AUTH_USERNAME = \"root@example.com\"\n\n");

    fs::write(&output_path, content).with_context(|| format!("Failed to write output file: {:?}", output_path))?;

    println!("Generated: {:?}", output_path);
    println!(
        "Run `mise run build-wasm` and `mise run ws-server` from {:?} to build and run this scenario.",
        output_dir
    );
    Ok(())
}

fn module_build_task_name(module_name: &str) -> String {
    format!("build-ws-{module_name}-module")
}

fn absolute_from(base: &Path, path: &Path) -> PathBuf {
    if path.is_absolute() {
        normalize_path(path)
    } else {
        normalize_path(&base.join(path))
    }
}

fn relative_path_from(from_dir: &Path, target: &Path) -> PathBuf {
    let from_components = normal_components(&normalize_path(from_dir));
    let target_components = normal_components(&normalize_path(target));
    let common_len = from_components
        .iter()
        .zip(target_components.iter())
        .take_while(|(from, target)| from == target)
        .count();

    let mut relative = PathBuf::new();
    for _ in common_len..from_components.len() {
        relative.push("..");
    }
    for component in target_components.iter().skip(common_len) {
        relative.push(component);
    }

    if relative.as_os_str().is_empty() {
        PathBuf::from(".")
    } else {
        relative
    }
}

fn normal_components(path: &Path) -> Vec<OsString> {
    path.components()
        .filter_map(|component| match component {
            Component::Normal(value) => Some(value.to_os_string()),
            _ => None,
        })
        .collect()
}

fn normalize_path(path: &Path) -> PathBuf {
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            Component::Prefix(prefix) => normalized.push(prefix.as_os_str()),
            Component::RootDir => normalized.push(Path::new("/")),
            Component::CurDir => {}
            Component::ParentDir => {
                normalized.pop();
            }
            Component::Normal(value) => normalized.push(value),
        }
    }
    normalized
}

fn cluster_module_names(cluster: &ClusterInput) -> Vec<String> {
    cluster
        .agents
        .iter()
        .flat_map(|agent| agent.modules.iter().map(|module| module.name.clone()))
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect()
}

fn toml_string(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len() + 2);
    escaped.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            _ => escaped.push(ch),
        }
    }
    escaped.push('"');
    escaped
}

#[cfg(test)]
mod test_generate_deployment;
