//! Wasmtime host bindings for the ws-wasi-runner `runner` world.
//!
//! Drives the same engine `wasmtime::component::bindgen!` expands, but writes the result to a checked-in
//! source file instead of generating it during the build. The macro read its WIT from
//! `../../generated/specs/wit` -- a path outside the crate -- which `cargo package` cannot include, so
//! `et-ws-wasi-runner` failed to compile from its own tarball and could not be published. Emitting the
//! bindings here leaves that crate self-contained and removes the last repo-relative `..` in a source file.
//!
//! `wasmtime-internal-wit-bindgen` is named `internal` upstream: treat its API as unstable and tied to the
//! pinned wasmtime version. `gen-specs-check` fails on any drift between this output and what is committed,
//! so a wasmtime bump that changes the generated code surfaces as a failing check rather than silently.
//!
//! WIT doc comments are copied through verbatim and land nested ~20 columns deep, so a comment in the WIT
//! that fits the editorconfig line length on its own can overflow once emitted here. That is why the world's
//! comments wrap well short of it; `editorconfig-check` on the emitted file is what enforces the result.
//!
//! prettyplease is the emitted file's only formatter, and `.rustfmt.toml` lists it under `ignore` for that
//! reason: running rustfmt over it as well is what breaks. prettyplease's output fits `max_width`, but
//! rustfmt rewraps one generated `impl ... where ...` to 126 columns and `error_on_line_overflow` then
//! rejects rustfmt's own result -- on a file nobody hand-edits.

use std::collections::HashMap;
use std::path::Path;

use wasmtime_internal_wit_bindgen::{FunctionConfig, FunctionFilter, FunctionFlags, Opts};
use wit_parser::Resolve;

use crate::Error;

/// The world in `generated/specs/wit/world.wit` the runner implements.
const WORLD: &str = "runner";

/// WIT types that map onto types the runner already defines, rather than generated ones.
///
/// Mirrors the `with:` block the `bindgen!` invocation carried, and must stay in step with the runner's
/// host module: a key here names a WIT item, the value the Rust path that replaces its generated form.
const WITH: [(&str, &str); 1] = [("wasi:keyvalue/store.bucket", "super::host::wasi_keyvalue::Bucket")];

/// Header prepended to the emitted file.
///
/// Carries the module docs and the lint expectations the generated surface needs; the generator owns the
/// whole file, so nothing here can be edited in place and survive the next run.
const HEADER: &str = r#"//! Wasmtime host bindings for the `runner` world.
//!
//! GENERATED by `mise run gen:wasmtime-bindings` (et-int-gen) from `generated/specs/wit`. Do not edit --
//! change the WIT or the generator instead, and regenerate. `gen-specs-check` fails when this drifts.
#![allow(
    unsafe_code,
    unused_variables,
    clippy::all,
    clippy::pedantic,
    clippy::restriction,
    clippy::missing_const_for_fn,
    clippy::too_long_first_doc_paragraph,
    clippy::type_repetition_in_bounds,
    clippy::use_self,
    reason = "generated from WIT by wasmtime-internal-wit-bindgen; we don't control its output. The group
    allows cover most of it, but Cargo's [lints] table passes -D per group on the command line, which an
    in-source group allow does not override -- so the four lints that still fire are named individually.
    A wasmtime bump that emits a fifth fails clippy until this list grows, which is the loud direction."
)]
"#;

/// Render the runner's host bindings from the WIT package rooted at `wit_dir`.
///
/// # Errors
///
/// Returns [`Error::Anyhow`] if the WIT fails to parse, names no `runner` world, or the generator rejects
/// the configuration, and [`Error::Syn`] if what it emits is not valid Rust.
pub fn render(wit_dir: &Path) -> Result<String, Error> {
    let mut resolve = Resolve::default();
    let (package, _files) = resolve.push_path(wit_dir)?;
    let world = resolve.select_world(&[package], Some(WORLD))?;

    // `imports: { default: async }` / `exports: { default: async }` from the macro invocation: every
    // import and export takes the async ABI, which is what lets a guest await a host `async func`.
    let mut async_default = FunctionConfig::new();
    async_default.push(FunctionFilter::Default, FunctionFlags::ASYNC);

    let opts = Opts {
        // rustfmt shells out to the toolchain's binary; prettyplease formats in-process instead, matching
        // how the REST client is rendered.
        rustfmt: false,
        with: WITH
            .iter()
            .map(|&(wit, rust)| (wit.to_owned(), rust.to_owned()))
            .collect::<HashMap<_, _>>(),
        imports: async_default.clone(),
        exports: async_default,
        ..Opts::default()
    };
    let generated = opts.generate(&mut resolve, world)?;
    let ast = syn::parse_file(&generated)?;
    Ok(format!("{HEADER}{}", prettyplease::unparse(&ast)))
}
