name: et_dart_math1
description: dart-math1 FedAvg module
version: 0.1.0
repository: https://github.com/edge-toolkit/core
publish_to: none

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  dio: ^5.9.2
  et_rest:
    path: ../../../generated/dart-rest

dev_dependencies:
  lints: ^6.0.0
