[package]
name = "et-test-helpers"
publish = true
description = "Low-dependency helpers for edge-toolkit tests"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
port_check.workspace = true
retry.workspace = true
temp-env.workspace = true

[lints]
workspace = true
