[project]
dependencies = ["et-ws", "et-ws-pyeye1", "et-ws-pyspeech1"]
description = "Python eye and speech detection demo"
license = "Apache-2.0 OR MIT"
name = "et-ws-pydemo1"
requires-python = ">=3.10"
version = "0.1.0"

[dependency-groups]
dev = ["pytest", "pytest-cov"]

[build-system]
build-backend = "uv_build"
requires = ["uv_build==0.11.8"]

[tool.uv.build-backend]
module-name = "pydemo1"
module-root = ""

[tool.uv.sources]
et-ws = { workspace = true }
et-ws-pyeye1 = { workspace = true }
et-ws-pyspeech1 = { workspace = true }

[tool.ws-module.dependencies]
"@mediapipe/tasks-vision" = "*"
et-model-eye1 = "*"
et-model-speech1 = "*"
et-ws = "*"
et-ws-pyeye1 = "*"
et-ws-pyspeech1 = "*"
onnxruntime-web = "*"
pyodide = "*"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
pythonpath = ["."]
