[package]
name = "et-ws-service"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
actix-web = "4"
actix-ws = "0.3"
chrono = { version = "0.4", features = ["serde"] }
edge-toolkit.workspace = true
futures-util = "0.3"
opentelemetry.workspace = true
serde.workspace = true
serde-inline-default.workspace = true
serde_default.workspace = true
serde_json.workspace = true
serde_yaml = "0.9"
tokio = { version = "1", features = ["macros", "rt", "sync", "time"] }
tracing.workspace = true
uuid.workspace = true
