use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::Path;

use edge_toolkit::input::ClusterInput;
use fs_err as fs;

use crate::error::CliError;
use crate::{ModuleSource, cluster_module_names, module_registry, resolve_module_sources};

/// Build context path of the hub image's Dockerfile, which the scenario image layers on top of.
const HUB_DOCKERFILE: &str = "services/ws-server/Dockerfile";

/// Guest languages the dependency stage loads so every `[tools]` pin is in scope.
///
/// A mise tool is only installable when the config declaring it is loaded, and the packages modules depend on
/// are spread across several guest configs (`npm:onnxruntime-web` in js, `http:pyodide` in python). Declaring
/// the full set costs nothing -- only the tools named on the `mise install` line are actually fetched.
const DEPS_MISE_ENV: &str = "dart,dotnet,java,js,kotlin,python,r,rust,zig";

pub fn generate_scenario_image(cluster: &ClusterInput, output_dir: &Path) -> Result<(), CliError> {
    let project_root = edge_toolkit::config::get_project_root();
    let ws_server_dir = project_root.join("services/ws-server");
    let registry = module_registry(&project_root, &ws_server_dir);
    let module_names = cluster_module_names(cluster);
    let sources = resolve_module_sources(&registry, &module_names)?;

    let mut repo_paths = Vec::new();
    let mut mise_tools = Vec::new();
    for (docker_path, source) in sources {
        match source {
            ModuleSource::Repo(repo_path) => repo_paths.push((repo_path, docker_path)),
            ModuleSource::MiseTool { tool, package } => mise_tools.push((tool, package, docker_path)),
        }
    }

    fs::write(
        output_dir.join("Dockerfile"),
        render_dockerfile(&cluster.cluster_name, &repo_paths, &mise_tools),
    )?;
    fs::write(
        output_dir.join("Dockerfile.dockerignore"),
        render_dockerignore(&project_root, &cluster.cluster_name, &repo_paths)?,
    )?;

    Ok(())
}

/// Render the scenario image, which layers this cluster's modules onto the hub image.
fn render_dockerfile(
    cluster_name: &str,
    repo_paths: &[(String, String)],
    mise_tools: &[(String, String, String)],
) -> String {
    let mut out = String::default();
    out.push_str("# syntax=docker/dockerfile:1\n\n");
    let _write_result = write!(
        out,
        concat!(
            "# AUTO-GENERATED by `et-cli` for the `{name}` scenario -- do not edit.\n",
            "# Regenerate with `mise run regen-verification`.\n",
            "#\n",
            "# The hub image ({hub}) carries no workflow modules at all, because which\n",
            "# modules a deployment serves is a per-cluster decision. This image is that decision made concrete: it\n",
            "# stages exactly the modules this cluster's agents declare, plus the packages those modules depend on,\n",
            "# into the `/app` paths the hub already scans.\n",
            "#\n",
            "# The sibling `Dockerfile.dockerignore` is what makes the COPYs below possible. The repository's root\n",
            "# `.dockerignore` drops every `*.wasm` and `*.onnx` so the CI images built from `./Dockerfile` stay\n",
            "# small; BuildKit uses this Dockerfile's own ignore file instead, which re-admits the built `pkg/`\n",
            "# directories and nothing else.\n",
            "\n",
        ),
        name = cluster_name,
        hub = HUB_DOCKERFILE,
    );

    if !mise_tools.is_empty() {
        out.push_str(&render_deps_stage(mise_tools));
    }

    // Each section above ends with its own blank line, so none of them start with one.
    // Doing it the other way round doubles the separator wherever two sections meet.
    out.push_str(concat!(
        "# `hub` is a named build context, not a stage defined here.\n",
        "# The generated compose file wires it to the hub service with `service:`, so compose builds the hub\n",
        "# image first and hands the result over under this name. That is also why the version-tag rule is\n",
        "# suppressed on the next line: hadolint reads `hub` as an untagged image, but there is no tag to give a\n",
        "# build context, and the image it resolves to is pinned by the hub Dockerfile rather than here.\n",
        "# hadolint ignore=DL3006\n",
        "FROM hub\n",
        "\n",
    ));

    // `pkg/` unconditionally, never probed for on disk.
    // Every module serves out of `pkg/`, whether that directory is committed (the JS shims) or produced by a
    // build (wasm-pack output, wheels). Probing for it makes this file depend on what happens to be built in the
    // working tree: CI checks out unbuilt Rust modules, found no `services/ws-modules/har1/pkg`, and emitted the
    // module root instead -- so the committed output and the CI regeneration disagreed and verification-check
    // failed. A module that genuinely has no `pkg/` now fails loudly at image build rather than silently
    // generating a different Dockerfile per machine.
    for (repo_path, docker_path) in repo_paths {
        let _write_result = writeln!(out, "COPY --chown=10001:10001 {repo_path}/pkg {docker_path}/pkg");
    }
    for (_, _, docker_path) in mise_tools {
        let _write_result = writeln!(
            out,
            "COPY --from=deps --chown=10001:10001 /staged{docker_path} {docker_path}"
        );
    }

    out
}

/// Render the stage that installs the mise-staged packages the cluster's modules depend on.
///
/// The repo's own `.mise/` configs and lockfiles are the version source, so nothing here pins a version that
/// could drift from what a workstation resolves; only the tool ids come from the module registry.
fn render_deps_stage(mise_tools: &[(String, String, String)]) -> String {
    let tools = mise_tools
        .iter()
        .map(|(tool, _, _)| tool.as_str())
        .collect::<Vec<_>>()
        .join(" ");
    let mut stage = String::default();
    stage.push_str(concat!(
        "# Stage the packages that live outside the repository.\n",
        "# These are published packages the modules load at runtime, provisioned by mise rather than built\n",
        "# here, so this stage installs them from the repo's own pins and copies each one to the `/app` path\n",
        "# the hub serves it from.\n",
        "FROM debian:bookworm-slim AS deps\n",
        "RUN bash <<'EOF'\n",
        "set -euo pipefail\n",
        "apt-get update\n",
        "apt-get install -y --no-install-recommends bash bzip2 ca-certificates curl git gzip tar unzip\n",
        "apt-get clean\n",
        "rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*.deb\n",
        "EOF\n",
        "\n",
        "# skipcq: DOK-DL4006\n",
        "RUN curl -fsSL https://mise.run | sh\n",
        "ENV HOME=/root\n",
        "ENV PATH=\"/root/.local/bin:/root/.local/share/mise/shims:${PATH}\"\n",
        "WORKDIR /workspace\n",
        "COPY .miserc.toml .miserc.toml\n",
        "COPY .mise/ .mise/\n",
        "RUN mise trust\n",
    ));
    let _write_result = writeln!(stage, "ENV MISE_ENV={DEPS_MISE_ENV}");
    if mise_tools.iter().any(|(tool, _, _)| tool.starts_with("npm:")) {
        // mise's npm backend shells out to npm, and refuses an `npm:` tool whose configured `node` dependency
        // is not installed yet ("requires configured install dependency 'node@22', but its selected version is
        // not installed"). Its version comes from the repo's own [tools] pin, like every other tool staged here.
        // The blank line after `EOF` is load-bearing, not formatting.
        // hadolint's parser reads the next instruction as a continuation of the heredoc without it and fails
        // with `unexpected 'E' expecting a new line followed by the next instruction`.
        stage.push_str(concat!(
            "RUN bash <<'EOF'\n",
            "set -euo pipefail\n",
            "mise install node\n",
            "EOF\n",
            "\n",
        ));
    }
    let _write_result = writeln!(stage, "ENV SCENARIO_TOOLS=\"{tools}\"");
    stage.push_str(concat!(
        "RUN bash <<'EOF'\n",
        "set -euo pipefail\n",
        "# Word-splitting SCENARIO_TOOLS is intentional; it is a space-separated tool list.\n",
        "# shellcheck disable=SC2086\n",
        "mise install ${SCENARIO_TOOLS}\n",
        "EOF\n",
        "\n",
    ));
    for (tool, package, docker_path) in mise_tools {
        let _write_result = writeln!(stage, "ENV STAGE_TOOL=\"{tool}\"");
        let _write_result = writeln!(stage, "ENV STAGE_PACKAGE=\"{package}\"");
        let _write_result = writeln!(stage, "ENV STAGE_DEST=\"/staged{docker_path}\"");
        // Locate the package rather than assume where the backend put it. The npm backend nests it under one
        // of several layouts (`lib/node_modules/`, `node_modules/`, or an aube virtual store below a
        // content-hashed directory) that vary by platform, so search for the named directory instead. The
        // named directory is tried FIRST and the install root only as a fallback: the npm backend drops its own
        // wrapper manifest (`"name": "mise-npm-install"`) at that root, so a root-first probe stages the
        // wrapper and the module is then served under the wrapper's name. The fallback is what covers an
        // archive-backed `http:` tool, which extracts flat so the root really is the package. `-L` and `cp -L`
        // resolve the symlinks the aube store is built from, so real files land in the image.
        stage.push_str(concat!(
            "RUN bash <<'EOF'\n",
            "set -euo pipefail\n",
            "root=\"$(mise where \"${STAGE_TOOL}\")\"\n",
            "src=\"$(find -L \"${root}\" -type d -name \"${STAGE_PACKAGE}\" ",
            "-exec test -f '{}/package.json' ';' -print -quit)\"\n",
            "if [ -z \"${src}\" ] && [ -f \"${root}/package.json\" ]; then\n",
            "    src=\"${root}\"\n",
            "fi\n",
            "if [ -z \"${src}\" ]; then\n",
            "    echo \"no ${STAGE_PACKAGE} package dir under the ${STAGE_TOOL} install at ${root}\" >&2\n",
            "    exit 1\n",
            "fi\n",
            "mkdir -p \"$(dirname \"${STAGE_DEST}\")\"\n",
            "cp -rL \"${src}\" \"${STAGE_DEST}\"\n",
            "EOF\n",
            "\n",
        ));
    }
    stage
}

/// Render the ignore file `BuildKit` applies to this Dockerfile in place of the repository root one.
///
/// It is the root file verbatim plus a re-include block, rather than a hand-picked subset, so a rule added to
/// `.gitignore` reaches this build too. Docker's matcher is last-match-wins and, unlike git's, still descends
/// into an excluded directory to honour a later negation, so the trailing block is enough to bring back the
/// built artifacts while every other exclusion keeps applying.
fn render_dockerignore(
    project_root: &Path,
    cluster_name: &str,
    repo_paths: &[(String, String)],
) -> Result<String, CliError> {
    let root = fs::read_to_string(project_root.join(".dockerignore"))?;
    let mut out = String::default();
    let _write_result = write!(
        out,
        concat!(
            "# AUTO-GENERATED by `et-cli` for the `{name}` scenario -- do not edit.\n",
            "# Regenerate with `mise run regen-verification`.\n",
            "#\n",
            "# BuildKit reads this file instead of the repository root `.dockerignore` when building the\n",
            "# Dockerfile beside it, so the root file keeps governing the CI images built from `./Dockerfile`\n",
            "# and only this build sees the re-includes at the end.\n",
            "\n",
        ),
        name = cluster_name,
    );
    out.push_str(&root);
    out.push_str(concat!(
        "\n",
        "# Re-admit the built module artifacts this scenario serves.\n",
        "# The rules above drop every `*.wasm` and `*.onnx`, which is what keeps the CI images small; these\n",
        "# negations put back the `pkg/` directories this image copies, and nothing else.\n",
    ));
    // A BTreeSet both de-duplicates paths shared by two modules and keeps the emitted order stable.
    let negations: BTreeSet<String> = repo_paths
        .iter()
        .map(|(repo_path, _)| format!("!{repo_path}/pkg/**"))
        .collect();
    for negation in negations {
        out.push_str(&negation);
        out.push('\n');
    }

    Ok(out)
}
