---
name: cargo-deny

"on":
  pull_request:
    paths:
      - Cargo.lock
      - Cargo.toml
      - "**/Cargo.toml"
      - deny.toml
      - .github/workflows/cargo-deny.yml
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

defaults:
  run:
    shell: bash

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cargo-deny
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny

      - name: Run cargo-deny
        run: cargo deny check
