---
name: check

"on":
  pull_request:
  push:
  # TODO: remove this after the workflow is verified to work on pull requests

permissions:
  id-token: write
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install mise
        uses: taiki-e/install-action@v2
        with:
          tool: mise

      - name: Install mise tools
        run: |
          mise settings add idiomatic_version_file_enable_tools "[]"
          mise install
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run checkers
        run: |
          mise run check
